apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    app.kubernetes.io/part-of: webapp
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
